name: Build and Deploy Code
on: [push, pull_rquest]
jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to dheeraj
        run: echo "hello dheeraj"
