name: Build and Deploy Code
on: [push, pull_rquest]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v3
      - name: say hi to dheeraj
        run: echo "hello dheeraj"
